const emotions = [{imgSrc: "./images/img-emotions/angry.png",name: "Anger", info: "Anger is an emotion characterized by feelings of displeasure, hostility, or frustration. You might recognize anger by physical sensations such as a rapid heartbeat, tense muscles, or a flushed face. Emotionally, you may feel a strong urge to react aggressively or assertively, and your thoughts might become focused on perceived injustices or irritations. Anger can manifest in various intensities, from mild annoyance to full-blown rage, and it often arises in response to situations that threaten your sense of control, safety, or well-being. Learning to identify and manage anger is essential for maintaining healthy relationships and emotional well-being."},
{imgSrc: "./images/img-emotions/excited.png", name: "Excitement" , info: "Excitement is an emotion characterized by anticipation, enthusiasm, and a heightened state of arousal. You might recognize excitement by physical sensations such as a racing heartbeat, butterflies in the stomach, or increased energy levels. Emotionally, you may feel eager, optimistic, and ready to engage with whatever is causing the excitement. Excitement often arises in response to positive events, such as receiving good news, embarking on a new adventure, or achieving a goal. It can be contagious, spreading joy and enthusiasm to those around you. Embracing and savoring moments of excitement can enhance overall well-being and add zest to life."},
{imgSrc: "./images/img-emotions/fear.png", name: "Fear", info: "Fear is an emotion characterized by a sense of apprehension, anxiety, or impending danger. You might recognize fear by physical sensations such as a racing heart, sweating, trembling, or a tightness in the chest. Emotionally, you may feel a strong desire to avoid or escape the perceived threat, and your thoughts might become focused on potential risks or negative outcomes. Fear can be triggered by various stimuli, including specific objects, situations, or even thoughts. It serves as a natural survival mechanism, alerting us to potential dangers and preparing us to respond defensively or seek safety. However, excessive or irrational fear can interfere with daily functioning and lead to avoidance behaviors. Learning to manage fear involves recognizing triggers, challenging irrational beliefs, and developing coping strategies to face threatening situations with courage and resilience."},
{imgSrc: "./images/img-emotions/frustrated.png", name: "Frustration", info: "Frustration is an emotion characterized by feelings of dissatisfaction, annoyance, or agitation when faced with obstacles or unmet goals. You might recognize frustration by physical sensations such as tension in the body, clenched fists, or a furrowed brow. Emotionally, you may feel impatient, irritable, or overwhelmed by the challenges you're encountering. Frustration often arises when you encounter barriers that impede your progress or when your expectations are not met. It can stem from various sources, including external circumstances, interpersonal conflicts, or internal struggles. Learning to manage frustration involves recognizing triggers, practicing patience and resilience, and finding constructive ways to address the underlying issues. By channeling frustration into productive action and problem-solving, you can overcome obstacles and achieve your goals more effectively."},
{imgSrc: "./images/img-emotions/glad.png", name: "Glad", info:`"Glad" is an emotion characterized by feelings of happiness, contentment, or satisfaction. You might recognize gladness by a sense of warmth or lightness in your mood, accompanied by a smile or a feeling of upliftment. Emotionally, you may feel a sense of relief, gratitude, or pleasure in response to positive events or experiences. Gladness can arise from various sources, such as achieving a goal, spending time with loved ones, or simply appreciating the small joys in life. It's a positive emotion that contributes to overall well-being and enhances resilience in the face of challenges. Cultivating a mindset of gratitude and focusing on moments of gladness can lead to greater happiness and fulfillment.`},
{imgSrc: "./images/img-emotions/happy.png", name: "Happiness", info: `"Happiness" is an emotion characterized by feelings of joy, contentment, and well-being. You might recognize happiness by a sense of lightness or buoyancy in your mood, accompanied by smiling, laughter, or a general sense of positivity. Emotionally, you may feel a deep sense of satisfaction, fulfillment, or pleasure in response to positive experiences, relationships, or accomplishments. Happiness can arise from various sources, such as spending time with loved ones, achieving personal goals, or engaging in activities that bring you joy. It's a fundamental human experience that contributes to overall mental and emotional health. Cultivating happiness involves nurturing positive relationships, practicing gratitude, and pursuing activities that align with your values and passions. Embracing moments of happiness can enhance resilience, foster greater well-being, and enrich your overall quality of life.`},
{imgSrc: "./images/img-emotions/offended.png", name: `Offended`, info: `"Offended" is an emotion characterized by feelings of hurt, resentment, or displeasure in response to perceived insults, disrespect, or injustices. You might recognize feeling offended by a sense of discomfort, unease, or defensiveness, accompanied by thoughts of being slighted or mistreated. Emotionally, you may experience anger, sadness, or indignation towards the person or situation that triggered the offense. Offense can arise from various sources, including insensitive remarks, actions that violate personal boundaries, or cultural misunderstandings. It's a natural response to feeling disrespected or devalued. Managing feelings of offense involves understanding the underlying reasons for your reaction, communicating assertively about your boundaries and feelings, and seeking resolution or reconciliation when appropriate. By addressing and processing feelings of offense constructively, you can promote understanding, strengthen relationships, and foster emotional resilience.`},
{imgSrc: "./images/img-emotions/sad.png", name: `Sadness`, info: `Sadness is an emotion characterized by feelings of sorrow, grief, or melancholy. You might recognize sadness by a heaviness or emptiness in your chest, accompanied by tears, a low mood, or a desire to withdraw from social interactions. Emotionally, you may experience a sense of loss, disappointment, or longing, often in response to negative events, such as the death of a loved one, a breakup, or a setback in life. Sadness is a natural and healthy response to difficult circumstances, and it's important to allow yourself to fully experience and express these feelings. Acknowledging sadness can lead to healing and growth, as it allows you to process and make sense of your emotions. Seeking support from loved ones or professional help when needed can provide comfort and assistance in navigating through periods of sadness. Remember that while sadness may feel overwhelming at times, it is a temporary state, and brighter days lie ahead.`},
{imgSrc: "./images/img-emotions/embarrassed.png", name: `Embarrassment`, info: `"Embarrassment" is an emotion characterized by feelings of self-consciousness, awkwardness, or discomfort in response to perceived social scrutiny or humiliation. You might recognize embarrassment by physical sensations such as blushing, sweating, or a rapid heartbeat, accompanied by thoughts of being judged, ridiculed, or exposed in a negative light. Emotionally, you may experience a desire to retreat or hide, as well as a sense of shame or regret over your actions or circumstances that led to the embarrassment. Embarrassment can arise from a variety of situations, including making a mistake in public, being caught in an awkward situation, or receiving unwanted attention. While it can be uncomfortable, embarrassment is a common and natural emotion that everyone experiences from time to time. Learning to accept and laugh at ourselves, as well as practicing self-compassion, can help alleviate feelings of embarrassment and promote greater confidence and resilience in social situations.`},
{imgSrc: "./images/img-emotions/board.png", name: `Boredom`, info: `"Boredom" is an emotion characterized by feelings of weariness, restlessness, or dissatisfaction arising from a lack of interest or stimulation in one's surroundings or activities. You might recognize boredom by a sense of lethargy, ennui, or a desire for something more engaging or meaningful. Emotionally, you may feel disinterested, unfulfilled, or even frustrated by the monotony of your current situation. Boredom can arise from various factors, such as repetitive tasks, lack of novelty, or insufficient mental or physical stimulation. While boredom is a common and natural experience, it can also serve as a signal that you may need to seek out new challenges, hobbies, or experiences to reignite your sense of curiosity and engagement with life. Embracing opportunities for learning, creativity, or exploration can help alleviate feelings of boredom and infuse your daily routine with a sense of purpose and excitement.`},
{imgSrc: "./images/img-emotions/hate.png", name: `Hate`, info: `"Hate" is an intense emotion characterized by feelings of extreme aversion, hostility, or animosity towards someone or something. You might recognize hatred by the intensity of your emotions, accompanied by thoughts of resentment, anger, or disdain towards the object of your hatred. Emotionally, you may experience a desire for harm or destruction towards the target of your hatred, as well as a sense of righteousness or justification for your feelings. Hatred can arise from various sources, such as perceived injustices, personal conflicts, or ideological differences. It often stems from deep-seated beliefs, past experiences, or societal influences. While hatred is a powerful and consuming emotion, it can also be destructive and harmful to both individuals and communities. Recognizing and addressing the underlying causes of hatred, fostering empathy and understanding, and promoting tolerance and compassion are essential steps towards healing and reconciliation.`},
{imgSrc: "./images/img-emotions/love.png", name: "Love" ,info:`"Love" is a profound and complex emotion characterized by feelings of affection, attachment, and care towards someone or something. You might recognize love by the warmth and tenderness it evokes, accompanied by thoughts of admiration, empathy, and devotion. Emotionally, you may experience a deep sense of connection and intimacy with the object of your love, as well as a desire for their well-being and happiness. Love can manifest in various forms, including romantic love, platonic love, familial love, or love for humanity or nature. It is a fundamental aspect of the human experience, contributing to feelings of fulfillment, belonging, and meaning in life. Cultivating love involves nurturing relationships, expressing gratitude and kindness, and practicing empathy and compassion towards oneself and others. Embracing love in its many forms can enrich our lives, foster emotional resilience, and promote greater harmony and understanding in the world.`}]

let emotionName = document.getElementById("emoton-name");
let emotionInfo = document.getElementById("emotion-info-p");
let emotionImg = document.getElementById("emotion-img");
const genarateEmotion = document.getElementById("genarate-emotion");


function getRendomEmotion() {
    let random = Math.floor(Math.random() * 12) +1;
    emotions.forEach((emotion, index) => {
            if(index == random) {
                emotionName.textContent = emotion.name;
                emotionInfo.textContent = emotion.info;
                emotionImg.setAttribute("src", emotion.imgSrc);
                
            }
        });
}

genarateEmotion.addEventListener("click", getRendomEmotion);